/**
 * Action types
 */
export const GET_INITIAL_QUESTIONS = 'GET_INITIAL_QUESTIONS'
export const ACTION_POST_QUESTION = 'ACTION_POST_QUESTION';
export const ACTION_UPDATE_QUESTION = 'ACTION_UPDATE_QUESTION';

export const ACTION_UPDATE_STATISTICS = 'ACTION_UPDATE_STATISTICS';
export const ACTION_UPDATE_LIST = 'ACTION_UPDATE_LIST';
export const ACTION_UPDATE_LEADERBOARD = 'ACTION_UPDATE_LEADERBOARD';

export const GET_INITIAL_USERS = 'GET_INITIAL_USERS';
export const ACTION_UPDATE_USERS = 'ACTION_UPDATE_USERS';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
