/**
 * Action types
 */
export const ACTION_POST_QUESTION = 'POST_QUESTION';
export const ACTION_UPDATE_STATISTICS = 'UPDATE_STATISTICS';
export const ACTION_UPDATE_LIST = 'UPDATE_LIST';
export const ACTION_UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD';

export const GET_INITIAL_QUESTIONS = 'GET_INITIAL_QUESTIONS'
export const GET_INITIAL_USERS = 'GET_INITIAL_USERS';

export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
